//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_room_dating
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string ReservingPersonID { get; set; }
        public string RoomName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int PeopleNumber { get; set; }
        public string Goal { get; set; }
        public string Equipments { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
    }
}
